/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2500
    gain: 12.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.0050
    device_name: /dev/ttyRM
    yaw_fix: 0.0
    pitch_fix: -0.2

    large_length: 0.2
    large_z: 0.06
    small_length: 0.04
    small_z: 0.02

    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector: 
  ros__parameters:
    debug: true
    detect_color: 0
    binary_thres: 100

    light.min_ratio: 0.05
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative","base","outpost"]

    aim_mode: 0


/armor_tracker:
  ros__parameters:
    target_frame: base_link
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.2
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 8e-4
      r_yaw: 3e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 0.8

      tracking_thres: 2
      lost_time_thres: 0.8

